// Estados e principais cidades do Brasil (as maiores/capitais + relevantes)
export const ESTADOS = {
  'AC': { nome:'Acre', cidades:['Rio Branco','Cruzeiro do Sul','Sena Madureira','Tarauacá','Feijó'] },
  'AL': { nome:'Alagoas', cidades:['Maceió','Arapiraca','Palmeira dos Índios','Rio Largo','União dos Palmares'] },
  'AP': { nome:'Amapá', cidades:['Macapá','Santana','Laranjal do Jari','Oiapoque','Mazagão'] },
  'AM': { nome:'Amazonas', cidades:['Manaus','Parintins','Itacoatiara','Manacapuru','Coari'] },
  'BA': { nome:'Bahia', cidades:['Salvador','Feira de Santana','Vitória da Conquista','Camaçari','Itabuna','Juazeiro','Ilhéus','Lauro de Freitas','Porto Seguro','Barreiras','Simões Filho','Alagoinhas'] },
  'CE': { nome:'Ceará', cidades:['Fortaleza','Caucaia','Juazeiro do Norte','Maracanaú','Sobral','Crato','Itapipoca'] },
  'DF': { nome:'Distrito Federal', cidades:['Brasília','Ceilândia','Taguatinga','Planaltina','Samambaia','Gama'] },
  'ES': { nome:'Espírito Santo', cidades:['Vitória','Vila Velha','Serra','Cariacica','Cachoeiro de Itapemirim','Linhares','Guarapari'] },
  'GO': { nome:'Goiás', cidades:['Goiânia','Aparecida de Goiânia','Anápolis','Rio Verde','Luziânia','Águas Lindas de Goiás'] },
  'MA': { nome:'Maranhão', cidades:['São Luís','Imperatriz','Timon','Caxias','Codó','Paço do Lumiar'] },
  'MT': { nome:'Mato Grosso', cidades:['Cuiabá','Várzea Grande','Rondonópolis','Sinop','Tangará da Serra','Cáceres'] },
  'MS': { nome:'Mato Grosso do Sul', cidades:['Campo Grande','Dourados','Três Lagoas','Corumbá','Ponta Porã'] },
  'MG': { nome:'Minas Gerais', cidades:['Belo Horizonte','Uberlândia','Contagem','Juiz de Fora','Betim','Montes Claros','Uberaba','Governador Valadares','Ipatinga','Sete Lagoas','Divinópolis','Poços de Caldas'] },
  'PA': { nome:'Pará', cidades:['Belém','Ananindeua','Santarém','Marabá','Parauapebas','Castanhal'] },
  'PB': { nome:'Paraíba', cidades:['João Pessoa','Campina Grande','Santa Rita','Patos','Bayeux','Sousa'] },
  'PR': { nome:'Paraná', cidades:['Curitiba','Londrina','Maringá','Ponta Grossa','Cascavel','São José dos Pinhais','Foz do Iguaçu','Colombo'] },
  'PE': { nome:'Pernambuco', cidades:['Recife','Jaboatão dos Guararapes','Olinda','Caruaru','Petrolina','Paulista','Cabo de Santo Agostinho'] },
  'PI': { nome:'Piauí', cidades:['Teresina','Parnaíba','Picos','Piripiri','Floriano','Campo Maior'] },
  'RJ': { nome:'Rio de Janeiro', cidades:['Rio de Janeiro','São Gonçalo','Duque de Caxias','Nova Iguaçu','Niterói','Belford Roxo','Campos dos Goytacazes','São João de Meriti','Petrópolis','Volta Redonda'] },
  'RN': { nome:'Rio Grande do Norte', cidades:['Natal','Mossoró','Parnamirim','São Gonçalo do Amarante','Macaíba','Ceará-Mirim'] },
  'RS': { nome:'Rio Grande do Sul', cidades:['Porto Alegre','Caxias do Sul','Canoas','Pelotas','Santa Maria','Gravataí','Novo Hamburgo','Viamão','São Leopoldo'] },
  'RO': { nome:'Rondônia', cidades:['Porto Velho','Ji-Paraná','Ariquemes','Vilhena','Cacoal','Rolim de Moura'] },
  'RR': { nome:'Roraima', cidades:['Boa Vista','Rorainópolis','Caracaraí','Alto Alegre','Mucajaí'] },
  'SC': { nome:'Santa Catarina', cidades:['Florianópolis','Joinville','Blumenau','São José','Chapecó','Itajaí','Criciúma','Jaraguá do Sul','Lages','Balneário Camboriú'] },
  'SP': { nome:'São Paulo', cidades:['São Paulo','Guarulhos','Campinas','São Bernardo do Campo','Santo André','Osasco','São José dos Campos','Ribeirão Preto','Sorocaba','Santos','Mauá','São José do Rio Preto','Mogi das Cruzes','Diadema','Piracicaba','Bauru','Jundiaí'] },
  'SE': { nome:'Sergipe', cidades:['Aracaju','Nossa Senhora do Socorro','Lagarto','Itabaiana','São Cristóvão','Estância'] },
  'TO': { nome:'Tocantins', cidades:['Palmas','Araguaína','Gurupi','Porto Nacional','Paraíso do Tocantins'] },
}
export const UFS = Object.keys(ESTADOS).sort()
